export const INDIAN_STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", 
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", 
  "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", 
  "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", 
  "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal",
  "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry"
];

export const DISTRICT_MAP: Record<string, string[]> = {
  "Maharashtra": [
    "Ahmednagar", "Akola", "Amravati", "Aurangabad (Chhatrapati Sambhajinagar)", 
    "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dhule", "Gadchiroli", 
    "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", 
    "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", 
    "Nashik", "Osmanabad", "Palghar", "Parbhani", "Pune", "Raigad", 
    "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", 
    "Wardha", "Washim", "Yavatmal"
  ],
  "Gujarat": ["Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar", "Botad", "Chhota Udepur", "Dahod", "Dang", "Devbhoomi Dwarka", "Gandhinagar", "Gir Somnath", "Jamnagar", "Junagadh", "Kutch", "Kheda", "Mahisagar", "Mehsana", "Morbi", "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot", "Sabarkantha", "Surat", "Surendranagar", "Tapi", "Vadodara", "Valsad"],
  "Karnataka": ["Bagalkot", "Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban", "Bidar", "Chamarajanagar", "Chikkaballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag", "Hassan", "Haveri", "Kalaburagi", "Kodagu", "Kolar", "Koppal", "Mandya", "Mysuru", "Raichur", "Ramanagara", "Shivamogga", "Tumakuru", "Udupi", "Uttara Kannada", "Vijayapura", "Yadgir"],
  // Add other states as needed...
};

export const TALUKA_MAP: Record<string, string[]> = {
  "Aurangabad (Chhatrapati Sambhajinagar)": [
    "Aurangabad", "Sillod", "Soegaon", "Phulambri", "Kannad", "Khultabad", "Paithan", "Gangapur", "Vaijapur"
  ],
  "Jalna": [
    "Jalna", "Badnapur", "Bhokardan", "Jafrabad", "Partur", "Mantha", "Ambad", "Ghansawangi"
  ],
  "Pune": [
    "Pune City", "Haveli", "Khed", "Ambegaon", "Junnat", "Shirur", "Daund", "Indapur", "Baramati", "Purandar", "Bhor", "Velhe", "Mulshi", "Maval"
  ]
};

export const RELIGIONS = [
  "Hindu", "Muslim", "Christian", "Sikh", "Buddhist", "Jain", "Parsi", "Other"
];

export const CASTE_CATEGORIES = [
  "Open", "OBC", "SC", "ST", "VJNT", "SBC", "EWS", "SEBC"
];

export const EXAMINATIONS = [
  "SSC", "HSC", "Graduation", "Post Graduation", "Diploma", "ITI", "Other"
];

export const BOARDS = [
  "Maharashtra State Board", 
  "CBSE (Central Board of Secondary Education)", 
  "ICSE (Indian Certificate of Secondary Education)", 
  "NIOS (National Institute of Open Schooling)",
  "UP Board (Uttar Pradesh)",
  "Bihar School Examination Board",
  "West Bengal Board of Secondary Education",
  "Karnataka Secondary Education Examination Board",
  "Tamil Nadu State Board",
  "Kerala State Education Board",
  "Rajasthan Board of Secondary Education",
  "Gujarat Secondary and Higher Secondary Education Board",
  "Andhra Pradesh Board of Intermediate Education",
  "Telangana State Board of Intermediate Education",
  "Savitribai Phule Pune University (SPPU)", 
  "Dr. Babasaheb Ambedkar Marathwada University (BAMU)", 
  "University of Mumbai", 
  "Shivaji University, Kolhapur", 
  "University of Delhi",
  "Jawaharlal Nehru University (JNU)",
  "Anna University (Tamil Nadu)",
  "Visvesvaraya Technological University (VTU - Karnataka)",
  "Jawaharlal Nehru Technological University (JNTU - Telangana/AP)",
  "Osmania University (Telangana)",
  "Indira Gandhi National Open University (IGNOU)",
  "Banaras Hindu University (BHU)",
  "Andhra University (Andhra Pradesh)",
  "Gauhati University (Assam)",
  "Patna University (Bihar)",
  "Gujarat University",
  "Kurukshetra University (Haryana)",
  "University of Kerala",
  "Barkatullah University (Madhya Pradesh)",
  "Utkal University (Odisha)",
  "Panjab University (Chandigarh)",
  "University of Rajasthan",
  "University of Calcutta (West Bengal)",
  "University of Lucknow (Uttar Pradesh)",
  "Madras University (Tamil Nadu)",
  "Bangalore University (Karnataka)",
  "Calicut University (Kerala)",
  "Himachal Pradesh University",
  "Jammu University",
  "Kashmir University",
  "International General Certificate of Secondary Education",
  "Aligarh Muslim University, Aligarh",
  "Andhra Pradesh Open School Society",
  "Assam Higher Secondary Education Council",
  "Assam Sanskrit Board (Guwahati)",
  "Banasthali Vidyapith",
  "Bhutan Higher Secondary Education Certificate (BHSEC)",
  "Bihar Board of Open Schooling and Examination, Patna, Bihar",
  "Bihar Intermediate Education Council, Patna (BIEC)",
  "Bihar Sanskrit Shiksha Board, Patna",
  "Bihar State Madrasa Education Board, Patna",
  "Board of High School and Intermediate Education, Uttar Pradesh",
  "Tamil Nadu Board of Higher Secondary Education",
  "AndhraPradeshBoardofIntermediateEducation",
  "Uttarakhand Board of School Education",
  "HaryanaBoardofSchoolEducation",
  "Board of Secondary Education, Odisha",
  "Board of Secondary Education, Andhra Pradesh",
  "Board of Secondary Education, Rajasthan, Ajmer",
  "Board of Secondary Education, Assam, Bamunimaidan, Guwahati",
  "Board of Secondary Education, Manipur, Imphal",
  "CBSE I(CBSE International)",
  "Central Board of Secondary Education, New Delhi",
  "Chhattisgarh Sanskrit Board, Raipur",
  "Chhattisgarh Board Of Open School Raipur",
  "Chhattisgarh Board of Secondary Education, Raipur",
  "Chhattisgarh Madrasa Board",
  "Council for the Indian School Certificate Examination",
  "Council of Higher Secondary Education, Manipur",
  "Council of Higher Secondary Education, Odisha",
  "Dayalbagh Educational Institute (Deemed University), Agra",
  "Edexcel, London (UK)",
  "Goa Board of Secondary & Higher Secondary Education",
  "Gujrat Secondary & Higher Secondary Education Board",
  "Himachal Pradesh Board of School Education",
  "International Baccalaureate",
  "Jamia Milia Islamia, New Delhi",
  "Jammu & Kashmir State Board of School Education",
  "Jharkhand Academic Council, Ranchi",
  "Karnataka Board of the Pre-University Education",
  "J S S Karnataka Open School",
  "Higher Secondary Education Govt of Kerala, Thiruvananthapuram",
  "Kerala Board of Public Examinations",
  "Kerala State Open School, Thiruvananthapuram",
  "Madhya Pradesh Board of Secondary Education",
  "Madhya Pradesh State Open School, Bhopal",
  "Maharashtra State Board of Secondary & Higher Secondary Education",
  "Maharishi Patanjali Sanskrit Sansthan, Bhopal",
  "Meghalaya Board of School Education",
  "Mizoram Board of School Education",
  "Nagaland Board of School Education",
  "National Institute of Open Schooling, Noida (Not eligible for Pharmacy course)",
  "Punjab School Education Board",
  "Rajasthan State Open School, Jaipur",
  "Rajiv Gandhi University of Knowledge Technologies, Hyderabad",
  "Rastriya Sanskrit Sansthan",
  "School Education Department, Govt of Tamil Nadu",
  "Telangana Open School Society",
  "Telangana Board of Intermediate Education",
  "The Haryana Open School",
  "The Jammu & Kashmir State Open School",
  "The Kerala State Higher Education Council",
  "The West Bengal Council of Rabindra Open Schooling",
  "Tripura Board of Secondary Education",
  "U. P. Board of Secondary Sanskrit Education Council",
  "Uttar Pradesh State Open School Board",
  "Uttranchal Siksha evam Pariksha Parisad",
  "Vishwa Bharti University, Shanti Niketan, Birbhum, Wb",
  "Vocational Higher Secondary Education Department, Govt of Kerala",
  "West Bengal Board of Madrasa Education",
  "West Bengal Council of Higher Secondary Education",
  "West Bengal State Council of Vocational Education & Training",
  "The Board of Open Schooling and Skill Education (BOSSE), Sikkim",
  "Apex Professional University, Pasighat, District East Siang, Arunachal Pradesh - 791102",
  "Arunachal University of Studies, NH-52, Namsai, Distt – Namsai - 792103, Arunachal Pradesh",
  "Arunodaya University, Lekhi Village, Naharlagun, Itanagar, Distt. Papum Pare, Arunachal Pradesh – 791110",
  "Himalayan University, 401, Takar Complex, Naharlagun, Itanagar, Distt – Papumpare – 791111, Arunachal Pradesh",
  "North East Frontier Technical University, Sibu-Puyi, Aalo (PO), West Siang (Distt.), Arunachal Pradesh –791001",
  "The Global University, Hollongi, Itanagar, Arunachal Pradesh",
  "The Indira Gandhi Technological & Medical Sciences University, Ziro, Arunachal Pradesh",
  "Venkateshwara Open University, Itanagar, Arunachal Pradesh",
  "Bharatiya Engineering Science and Technology Innovation University, Gownivaripalli, Gorantla Mandal, Anantapur, Andhra Pradesh",
  "Centurian University of Technology and Management, Gidijala Junction, Anandpuram Mandal, Visakhapatnam- 531173, Andhra Pradesh",
  "KREA University, 5655, Central, Expressway, Sri City-517646, Andhra Pradesh",
  "Mohan Babu University, Sree Sainath Nagar, Tirupati, Andhra Pradesh- 517102",
  "Saveetha Amaravati University, 3rd Floor, Vaishnavi Complex, Opposite Executive Club, Vijayawada- 520008, Andhra Pradesh",
  "SRM University, Neerukonda-Kuragallu Village, mangalagiri Mandal, Guntur, Dist- 522502, Andhra Pradesh",
  "The Appolo University, The Apollo KnowledgeMurukambattu, Chittoor-517127, Andhra Pradesh",
  "VIT-AP University, Amaravati- 522237, Andhra Pradesh",
  "Assam Don Bosco University, Azara, Guwahati",
  "Assam Down Town University, Sankar Madhab Path, Gandhi Nagar, Panikhaiti, Guwahati – 781 036",
  "Auniati University, Kaliapani, Teok, Dist- Jorhat, Assam",
  "Girijananda Chowdhury University Assam, Hathkhowapara, Azara, Guwahati – 781017, District – Kamrup (Metro), Assam",
  "Krishnaguru Adhyatmik Vishwavidyalaya, Nasatra, Barpeta, Assam- 781307",
  "Mahapurusha Srimanta Sankaradeva Viswavidyalaya, Srimanta Sankaradeva Sangha Complex, Haladhar Bhuyan Path, Kalongpar, Nagaon-782001, Assam",
  "Pragjyotishpur University, Hajongbari, P.O- Chandrapur under Panbari Mouza, Kamrup, Metropolitan District, Guwahati, Assam- 781050",
  "The Assam Kaziranga University, Jorhat, Assam",
  "The Assam Royal Global University, Betkuchi, Opp. Tirupati Balaji Temple, NH-37, Guwahati – 781035, Assam",
  "Al-Karim University, Near Katihar-Purnea Road, Sirsa, Karim Bagh, Katihar- 854106, Bihar",
  "Amity University, Rupaspur, Bailey Road, Patna- 801503, Bihar",
  "Dr. C.V.Raman University, Block- Bhagwanpur, NH- 77, (PatnaMuzaffarpur Highwary), District- Vaishali- 844114, Bihar",
  "Gopal Narayan Singh University, Jamuhar, PO- Jamuhar, DistRohtas- 821305, Bihar",
  "Mata Gujri University, Purabpali Road, Kishanganj- 855107, Bihar",
  "Sandip University, Village – Sijoul, Dist. – Madhubani – 847235, Bihar",
  "K.K. University, Berauti, Nepura, Bihar Sharif, Nalanda, Bihar – 803115",
  "AAFT University of Media and Arts, Vill- Maath, Tehsil-Tilda, Dist-Raipur, Chhattisgarh",
  "Amity University, Village-Manth, Tehsil-Tilda, Distt-Raipur, Chhattisgarh",
  "Anjaneya University, Knowledge Village, Naradha, Near Vidhan Sabha, Raipur, Chhattisgarh- 493111",
  "Bharti Vishwavidyalaya, Chandkhuri, Durg, Chhattisgarh – 491001",
  "Dev Sanskriti Vishwavidyalaya, Village - Sankra Kumhari, District – Durg – 490042, Chhattisgarh",
  "Dr. C.V. Raman University, Kargi Road, Kota, Bilaspur",
  "ICFAI University, NH-6, Raipur-Bhilai Road, Gram-Chorha, RI Circle, Ahiwara, Dhamdha, Dist. – Durg, Chhattisgarh",
  "ISBM University, Village – Nawapara (Kosmi) Block, tehsil – Chhura, Dist – Gariyaband – 493996, Chhattisgarh",
  "ITM University, PH No. 137, Uparwara, Naya Raipur, Dt. Raipur – 493661, Chhattisgarh",
  "Kalinga University, Raipur-492101, Chhattisgarh",
  "K.K.Modi University, Khasra No. 72, 73, 75, 217 & 220 Village Mahmara, Jalbandha (Rasmada) Road, District Durg, Chattisgarh",
  "Maharishi University of Management and Technology, Post: Mangla, Bilaspur – 495 001",
  "MATS University, Arang Kharora Highway, Gram Panchayat: Gullu, Village: Gullu, Tehsil : Arang, District: Raipur",
  "O.P. Jindal University, Knowledge Park, Gharghoda Road, Punjipathra, Raigarh-496001, Chhattisgarh",
  "Shri Rawatpura Sarkar University, NH-30, New Dhamtari Road, Post- Mana, Raipur-492015, Chhattisgarh",
  "Shri Shankaracharaya Professional University, Village Junwani, Bhilai, Dist Durg, Chhattisgarh- 490020",
  "India International University of Legal Education and Research, Upasnagar, Sancoale, Airport Road, South Goa, Goa – 403710",
  "Adani University, Shantigram Township, Near Vaishnodevi Circle, SG Highway, Ahmedabad, Gujarat - 382241",
  "Ahmedabad University, AES Bungalow # 2, Navrangpura, Ahmedabad – 380 009",
  "Anant National University, Sanskardham Campus, BhopalGhuma-Sanand Road, Ahmedabad, Gujarat – 382115",
  "Atmiya University, Yogidham Gurukul, Kalawad Road, Rajkokt360005, Gujarat",
  "AURO University of Hospitality and Management, Surat, Gujarat",
  "Bhagwan Mahavir University, VIP Road, Vesu, Surat, Gujarat",
  "Bhaikaka University, Gokal Nagar, Karamsad- 388325, Gujarat",
  "CEPT University (Formerly Centre for Environmental Planning and Technology University), University Road, Narvrangpura Ahemdabad-380009, Gujarat",
  "Charotar University of Science & Technology, Changa – 388 421, Distt – Anand",
  "C.U. Shah University, Surendranagar-Ahmedabad State Highway, Near Kothariya Village, Wadhwan City – 363030, Dt. Surendranagar, Gujarat",
  "Darshan University, Rajkot-Morbi Highway, At.Hadala Ta. Distt. Rajkot – 363650, Gujarat",
  "Dhirubhai Ambani Institute of Information and Communication Technology, Gandhinagar, Post Box No. 4, Gandhinagar-382 007",
  "Drs. Kiran & Pallavi Patel Global University (KPGU), Krishna Education Campus, Block No.136/P, Vadodara-Mumbai NH#8, Varnama, Vadodara – 391243, Gujarat",
  "Dr. Subhash University, Dr. Subhash Road, Junagadh – 362 001, Gujarat",
  "Ganpat University, Ganpat Vidyanagar, Mehsana, Goazaria Highway, District Mehsana – 382 711",
  "Gandhinagar University, Village: Moti Bhoyan, Khatraj-Kalol Road, Ta: Kalol, District Ganghinagar - 382721, Gujarat",
  "G.L.S. University, Gujarat Law Society Campus, Opp. Law Garden, Ellisbridge, Ahmedabad-380006, Gujarat",
  "Gokul Global University, Gokul Educational Campus, Near GRSL, Sujanpur Patia, Sidhpur, Dist. Patan, Gujarat – 384151",
  "Gujarat Maritime University, Gandhinagar, Gujarat",
  "GSFC University, Vigyan Bhavan, PO Fertilizernagar – 391750, Dist. Vadodara, Gujarat",
  "Gyanmanjari Innovative University, Survey No. 30, Sidsar Road, Bhavnagar- 364060, Gujarat",
  "Indrashil University, On Ahmedabad-Mehsana Highway, Take Left from Kalapi Hotel, Near Chhataral GIDC, Rajpur, Taluka - Kadi, District – Mehsana – 382715 , Gujarat",
  "Indus University, Indus Campus, Rancharda, Via-Thaltej, Ahmedabad – 382115, Gujarat",
  "Indian Institute of Public Health, Gandhinagar, Opposite Air Force Headquarters, Near Lekawada Bus Stop, GandhinagarChiloda Road, CRPF. P.O- Lekawada, Gandhinagar- 382042, Gujarat",
  "Institute of Advanced Research, Institutional Area, Koba, Gandhinagar – 382007, Gujarat",
  "ITM (SLS) Baroda University, Paldi, Near Jarod, VadodaraHalol Highway, Vadodara- 391510, Gujarat",
  "ITM-Vocational University, Plot 6512, Ajwa Nimeta Road, Ravaal Taluka, Waghodia, Vadodara, Gujarat",
  "J.G.University, Uvarsad, Dist- Gandhinagar- 380054, Gujarat",
  "Kadi Sarva Vishwavidyalaya, Sarva Vidyalaya Campus, Sector 15/23, Gandhinagar",
  "Karnavati University, 907/A, Uvarsad – 382422, Dt. Gandhinagar, Gujarat",
  "K.N University, SR. No. 115, 199, 311, 201,-202, 26, Smt. K.N Patel International School, Near KNPIS Circle, Vodafone Tower Lane, Gota, Ahmedabad- 382481, Gujarat",
  "Lakulish Yoga University, “Lotus View” Opp. Nirma University, S.G. Highway, Chharodi, Ahmedabad-382481, Gujarat",
  "Lok Jagruti Kendra University, FP No. 74, 100+113, TPS No.86, (Sarkhej-okaf-Fatewadi, Makrba), Dist Ahmedabad, Gujarat",
  "Lokbharati University for Rural Innovation, At. Sanosara, Ta. Sihor, Dist. Bhavnagar, Gujarat - 364230",
  "Maganbhai Adenwala Mahagujarat University, I.S. Ayurved Mahavidyalaya, College Road, Nadiad - 387001, Gujarat",
  "Marwadi University, Rajkot-Morbi Highway, Rajkot – 360003, Gujarat",
  "Monark University, At & Post Vahelal, Naroda-Dahegam Road, Ta. Dascroi, District Ahmedabad, Gujarat – 382330",
  "Navrachana University, Vasna-Bhayli Road, Vadodara – 391410, Gujarat",
  "Nirma University, Sarkhej, Gandhinagar Highway, VillageChharodi, Ahmedabad",
  "Noble University, Noble Group of Institutions, Parth Vatika, Bhesan Road, Near Bamangam, Ta. & Distt., Junagadh - 362310, Gujarat",
  "Pandit Deendayal Energy University (Formerly Pandit Deendayal Petroleum University), Knowledge Corridor, Raisan, Dist. Gandhinagar – 382007, Gujarat",
  "Parul University, PO Limda, Tal – Waghodia, Dist. Vadodara391760, Gujarat",
  "Plastindia International University, Dungra, GIDC, VAPI, Dist. Valsad – 396195, Gujarat",
  "P. P. Savani University, NH-8, GETCO, Near Biltech, Village – Dhamdod, Kosamba, Ta – Mangrol, Dist – Surat – 394125, Gujarat",
  "R.K. University, Rajkot-Bhavnagar Highway, Kasturbadham, Rajkot, Gujarat",
  "Rai University, Ahmedabad, Gujarat",
  "Rajju Shroff Rofel University (RSRU), Survey No. 78-79, ROFEL Campus, Namdha- Vapi, Valsad- 396191, Gujarat",
  "Sigma University, At & PO. Bakrol, Ajwa- Nimeta Road, Ta: Waghodiya, Vadodara- 390019, Gujarat",
  "SKIPS University, Plot No. 411, Sanavad, Kalol, Gandhinagar - 382721, Gujarat",
  "Sabarmati University, (Formerly Calorx Teacher’s University), Ahmadabad",
  "Sankalchand Patel University, Sankalchand Patel Vidyadham, Visanagar-384315, Gujarat",
  "Sardar Vallabhbhai Global University, Chimanbhai Patel Institute Campus, Opposite Karnavati Club, Near Sahpath IV, Ahmedabad- 380015, Gujarat",
  "Sarvajanik University, M.T.B College Campus, Opposite Chowpati, Athwalines, Surat, Gujarat- 395001",
  "Shreyarth University, C/o Gujarat Samachar Bhavan, Khanpur, Ahmedabad- 380001, Gujarat",
  "Silver Oak University, S.G.Highway, Gota, Ahmedabad382481, Gujarat",
  "Surendranagar University, Shree Pandit Nathulalji Vyas Technical Campus, Surendranagar-Ahmedabad Highway, Nr.Kothariya Village, At Wadhwan- 363030, Gujarat",
  "Swarnim Startup & Innovation University, Bhoyan Rathod Rathod, Opp. IFFCO, Adalaj-Sertha Road, Gandhinagar – 382420, Gujarat",
  "Swaminarayan University, Shree Swaminarayan Vishvamangal Gurukul, Ahmedbad-Mehsana Highway, At & PO – Saij, Tal. - Kalol, District Gandhinagar, Gujarat - 382725",
  "Team Lease Skills University, Tarsali-Vadodara Road, Tarsali Bypass, Vadodara – 390009, Gujarat",
  "The Charutar Vidya Mandal(CVM) University, Opposite Shastri Maidan, Beside BVM College, Vallabh Vidyanagar, Dist Anand, Gujarat",
  "Transstadia University, Opposite Kankaria Gate No. 3, Kankaria, Ahmedabad – 380 022, Gujarat",
  "UKA Tarsadia University, Maliba Campus, Gopal vidyanagar, Baroli-Mahuva Road, Dist. Surat, Gujarat",
  "Vanita Vishram Women’s University, Vanita Vishram Campus, Jawaharlal Nehru Marg, Athwa Gate, Surat – 395001 (Gujarat)",
  "UPL University of Sustainable Technology, Block No. 402, At & PO Vataria, Taluka Valia, District Bharuch, Gujarat",
  "Vidhyadeep University, At Post – Anita, Kim-Olpad Highway, Ta.- Olpad, District - Surat - 394110, Gujarat",
  "Al-Falah University, Faridabad, Haryana",
  "Amity University, Amity Education Valley, Panchgaon, Manesar, Distt. – Gurgaon-122 413, Haryana",
  "Apeejay Stya University, Palwal Road, Sohna, Gurgaon – 122 103, Haryana",
  "Ashoka University, Plot No. 2, Rajiv Gandhi Education City, Kundli, NCR, Sonepat, Haryana",
  "Baba Mast Nath University, Asthal Bohar, Rohtak, Haryana – 124 021",
  "BML Munjal University, 67th KM Stone, NH-8, Sidhrawali, Dist. Gurgaon – 123 413, Haryana",
  "G.D. Goenka University, G.D. Goenka Education City, Gurgaon sohna Road, Gurgaon, Haryana – 122 103",
  "Geeta University, 1326, HUDA Sector 12, Panipat – 132103 Haryana",
  "IILM University, 1, Knowledge Centre, Golf Course Road, Sector- 53, Gurugram- 122003, Haryana",
  "Jagan Nath University, State Highway 22, Bahadurgarh-Jhajjar Road,Jhajjar – 124 507, Haryana",
  "K.R. Mangalam University, Sohna Road, Gurgaon, Haryana – 122 103",
  "Manav Rachna University, Sector – 43, Delhi-Surajkund Road, Faridabad, Haryana",
  "M.V.N. University, Palwal, Haryana",
  "Maharashi Markandeshwar University, Sadopur, Distt. Ambala, Haryana",
  "NIILM University, 9 KM Milestone, NH-65, Kaithal – 136 027, Haryana",
  "Om Sterling Global University, NH-52, Hisar-Chandigarh Road, Hisar- 125001, Haryana",
  "O.P. Jindal Global University, Sonipat",
  "PDM University, Post Box No. 15, Sector – 3A, Sarai Aurangabad, Bahadurgarh-124507, Haryana",
  "Rishihood University, NH-44(GT Road), Near Bahalgarh Chowk, NCR of Delhi, Sonipath, Haryana- 131021",
  "Shree Guru Gobind Singh Tricentenary University, Farukh Nagar Road, Budhera, Distt. Gurgaon – 122 505, Haryana",
  "SRM University, Plot No. 39, Rajiv Gandhi Education City, Delhi-NCR, Sonepat-Kundli Urban Complex, Haryana – 131 029",
  "Starex University, NH-8, Village – Binola, PO – Bhorakalan, Gurugram, Haryana",
  "Sushant University (Formerly Ansal University), Guraon, Haryana",
  "The Northcap University (Formerly ITM University), HUDA Sector 23 A, Gurgoan-122107, Haryana",
  "World University of Design, Plot No- 1, Rajiv Gandhi Education City, Rai, Delhi- NCR, Sonipat- 131029, Haryana",
  "Abhilashi University, Chailchowk (Chachiot), Distt. Mandi, Himachal Pradesh",
  "A.P.G. (Alakh Prakash Goyal) Shimla University, Shimla, Himachal Pradesh",
  "Arni University, Kathgarh, Tehsil Indora, Distt. Kangra (H.P)",
  "Baddi University of Emerging Sciences & Technology, Makhnumajra, BADDI, District – Solan",
  "Bahra University, VPO – Waknaghat, Tehsil – Kandaghat, Distt. – Solan, Himachal Pradesh",
  "Career Point University, Hamirpur, Himachal Pradesh",
  "Chitkara University, HIMUDA Education Hub, Kallujhanda(Barotiwala), Distt.-Solan – 174 103",
  "Eternal University, Baru Sahib Himachal",
  "I.E.C. (India Education Centre) University, Baddi, Solan, Himachal Pradesh",
  "ICFAI University, HIMUDA Education Hub, Kalujhinda, PO Mandhala, Via Barotiwala, Baddi, Solan Distt., Himachal Pradesh – 174 103",
  "Indus International University, V.P.O. Bathu, Tehsil Haroli, Distt. – Una, Himachal Pradesh – 174 301",
  "Jaypee University of Information Technology, Distt-Solan-173 215",
  "Maharishi Markandeshwar University, Kumarhatti, Sultanpur Road, Solan – 173 229, Himachal Pradesh",
  "Maharaja Agrasen University, Atal Shiksha Kunj, Distt – Solan – 174 103, Himachal Pradesh",
  "Manav Bharti University, Solan, H.P",
  "Shoolini University of Biotechnology and Management Sciences, Solan",
  "Sri Sai University, Palampur, Himachal Pradesh",
  "Amity University, Ranchi City Campus, Niwaranpur, Main Road, Ranchi, Jharkhand",
  "AISECT University, Matwari Chowk, Infront of Gandhi Maidan, Hazaribagh, Jharkhand",
  "ARKA Jain University, Opp. Kerala Public School, Mohanpur, Gamharia, Dist – Seraikela Kharsawan – 832108, Jharkhand",
  "Babu Dinesh Singh University, Farathiya, Garhwa, Jharkhand",
  "Capital University, Ranchi-Patna Main Road, District- Koderma, Jharkhand- 825410",
  "Durga Soren University, Shivam Trust, Bompass Town, Deoghar, Jharkhand",
  "Jharkhand Rai University, Kamre, Ratu Road, Ranchi835222, Jharkhand",
  "Netaji Subhas University, Pokhari, PO- Bhilai Pahari, PSMGM, Dist- East Singhbhum, Jamshedpur-831012, Jharkhand",
  "Pragyan International University, Bariatu Road, Booty More, PO – RMCH, Ranchi – 834009, Jharkhand",
  "Radha Govind University, Radha Govind Nagar, Lalki Ghati, Ramgarh- 829122, Jharkhand",
  "Ram Krishana Dharmarth Foundation University, 604, 5th Floor, Gopal Marketing Complex, Near Argora Chouk, Ranchi834002, Jharkhand",
  "Ramchandra Chandravansi University, Nawadihkala, PO & PS Bishrampur, Palamu- 822132, Jharkhand",
  "Sai Nath University, Ranchi, Jharkhand",
  "Sarla Birla University, Birla Campus, Village – Ara, PO – Mahilong, Ranchi-Purulia Highway, Ranchi – 835103, Jharkhand",
  "Sona Devi University, Kitadih, PO & PS Ghatsila, North Maubhandar, East Singhbhum, Jharkhand",
  "Srinath University, Dindli, Adityapur, Jamshedpur – 831013, Jharkhand",
  "The Institute of Chartered Financial Analysts of India University, Grand Emerald Building, Between Road No. 1 & 2, Ashok Nagar, Ranchi – 834 202, Jharkhand",
  "Usha Martin University, 12 Mile, Ranchi Khunti Road, NH-75, Ranchi – 835221, Jharkhand",
  "YBN University, Panchwati South Railway Colony, Ranchi – 834001, Jharkhand",
  "Adichunchanagiri University, NH-75, Tq- Nagamangala, DistMandya, B.G.Nagara- 571448, Karnataka",
  "Alliance University, Bangalore (Karnataka)",
  "Amity University, Opposite to Office.NH 648 (Old 207) Beerasandra, Alurududdhanahalli Post, Devanahalli Taluk, Begnaluru Rural District- 562110, Karnataka",
  "Atria University, ASKB Campus, 1st Main Road, AGS Colony, Anandhnagar, Hebbal, Bengaluru - 560024 Karnataka",
  "Azim Premji University, 134, Doddakanneli, Next to Wipro Corporate Office, Sarjapur Road, Bangalore, Karnataka",
  "Chanakya University, Brigade Orchards, Rayasandra Village, Kasaba Hobli, Devanahalli Taluk, Bengaluru Rural District, Karnataka",
  "CMR University, 2,3rd, ‘C’, 6th Main Road, 2nd Block, BRBR Layout, Kalyan Nagar, Bangalore – 560 043, Karnataka",
  "Dayananda Sagar University, Shavige Malleshwara Hills, Kumaraswamy Layout, Bangalore-560078, Karnataka",
  "Garden City University, GCC House, 340, 5th Main, Indira nagar Double Road, 1st Stage, Indiranagar, Bangalore – 560038, Karnataka",
  "G.M University, Karur Village, Kasaba Hobli, Davanagere District, Karnataka",
  "JSS Science & Technology University, JSS Technical Institutions Campus, Mysuru – 570006. Karnataka",
  "Khaja Bandanawaz University, Administrative Building, Khaja Bandanawaz University Campus, Rauza-i Buzurg, Kalaburagi585104, Karnataka",
  "Kishkinda University, City Campus, Ballari Business College, Siruguppa Road, Ballari- 583103, Karnataka",
  "KLE Technological University, B.V. Bhoomaraddi College Campus, Vidyanagar, Hubballi – 580031, Karnataka",
  "M.S. Ramaiah University of Applied Sciences, Administrative Block, New BEL Road, MSRIT Post, Bangalore – 560 054, Karnataka",
  "PES University, 100 Feet Ring Road , BSK III Stage, Bangalore – 560 085 (Karnataka)",
  "Presidency University (Karnataka), Dibbur &Ittagalpura Village, Hesaraghatta Hobli, Bangalore (Karnataka)",
  "Reva University, Kattigenhalli, Yelhanka, Bangalore – 560 064, Karnataka",
  "Rai Technology University, Doddaballapur Nelmangala Road, SH-74, Off Highway 207, Doddaballapur Taluk, Bangalore561204 (Karnataka)",
  "RV University, RVU Administrative Building, RV Vidyaniketan Post, Mysuru Road, Bengaluru- 560059, Karnataka",
  "Sharnbasva University, Kalaburgi (Gulbagra) – 585103, Karnataka",
  "Shri Dharmasthala Manjunatheshwara University, 6th Floor, Manjushree Building, SDM College of Medical Sciences & Hospital Campus, Sattur, Dharwad- 580009, Karnataka",
  "Sri Jagadhguru Murugarajendra University, SJM Camus, Chitradurga- 577502, Karnataka",
  "Srinivas University, Srinivas Group of Colleges Campus, Srinivas Nagar, Mukka, Surathkal, Mangalore-574146",
  "Sri Sathya Sai University for Human Excellence, Sri Sathya Sai Vidyaniketanam Campus, Navanihala, Post- Okali, TalukKamalapur, Dist- Kalburagi- 585313, Karnataka",
  "St. Joseph’s University, P.O. Box 27094, #36, Lalbagh Road, Bengaluru – 560 027, Karnataka",
  "The University of Trans-Disciplinary Health Sciences and Technology, 74/2, Jarakabande Kaval, Yelahanka, Via Attur Post, Bangalore-560064, Karnataka",
  "Vidyashilp University, No.125 Bettenahalli, Kundana Hobli, Chapparkallu Road, Bengaluru- 562110, Karnataka",
  "CMJ University, Shillong (Meghalaya)",
  "Mahatma Gandhi University, 13th Mile, G.S.Road, Khanapara, Dist- Ri-Bhoi, Meghalaya- 793101",
  "Martin Luther Christian University, Dongktieh, Nongrah, Block-1, Shillong – 793006, Meghalaya",
  "North East Adventist University, Khliehtyrshi, P.O Thadlaskein793151, West Jaintia Hills District, Meghalaya",
  "The Institute of Chartered Financial Analysts of India University, 4th Floor, Near Sundari Hotel, Circular Raod, Tura Bazar, Tura – 794 001",
  "University of Science & Technology, MeghalayaTechno City, Kling Road, Baridua, G.S.Road, 9th Mile, Dist- Ri-Bhoi, Meghalaya- 793101",
  "Maharashtra Institute of Technology University of Meghalaya (Formerly University of Technology & Management), Sunny view, Nonghilliang, Nongthymmai, Shillong – 793014, Meghalaya",
  "William Carey University, Nongmensong, Umkdait, Shillong – 793 019, Meghalaya",
  "The Institute of Chartered Financial Analysts of India University, Salem Veng, Chaltlang, Aizawal – 798 012, Mizoram",
  "Abhyuday University, Gram Magriya, Khandwa Road, Khargone, Madhya Pradesh",
  "A.K.S. University, Satna, Madhya Pradesh",
  "Amaltas University, Dewas, Dewas-Ujjain State Highway, Bangar, District- Dewas, Madhya Pradesh",
  "Azim Premji University, Bypass Road, Kanhasaiya Tehsil- Huzur, Bhopal, Madhya Pradesh",
  "Rabindranath Tagore University (Formerly AISECT University) Village- Mendua, Bhopal-Chiklod Road, Tehsil Goharganj, Dist Raisen, Madhya Pradesh",
  "Amity University, Maharajpura Dang, Gwalior, Madhya Pradesh",
  "Aryavart University, National Highway- 46, Village Jharkheda, Tehsil-Shyampur, District- Sehore, Madhya Pradesh",
  "Avantika University, Vishwanathpuram, Lekoda Village, Ujjain – 456 006, Madhya Pradesh",
  "Bhabha University, NH-12, Hoshangabad Road, Jatkhedi, Bhopal- 462026, Madhya Pradesh",
  "Chirayu University, Bhopal-Indore Highyway, Near Bairagarh, Bhainsakhedi, Bhopal- 462030, Madhya Pradesh",
  "Dr. A.P.J. Abdul Kalam University, Indore-Devas Bypass Road, Village – Arandia, Post – Jhalaria, Madhya Pradesh – 452016",
  "Dr. C. V. Raman University, Khandwa-Indore Road, PostChhaigaon Makhan, Khandwa- 450771, Madhya Pradesh",
  "Dr. Preeti Global University, Gram Dinara, Teh- Karera, DistrictShivpuri, Madhya Pradesh 473665",
  "Eklavya University, Ojaswini Nagar, Sagar Road, Damoh, Madhya Pradesh",
  "G.H. Raisoni University, Village – Saikheda, Dhoda Borgaon, Tah – Saunsar, Dist – Chhindwara, Madhya Pradesh",
  "Gyanveer University, Village- Maa-Emliya, PH- 20, BlockRahatgarh, District- Sagar, Madhya Pradesh",
  "I.E.S University, IES Campus, Ratibad Main Road, Bhopal462044 Madhya Pradesh",
  "ITM University, ITM Campus, Opp. Sithouli Rly. Station, NH – 75, Jhansi Road, Gwalior-474 001, Madhya Pradesh",
  "Jagran Lakecity University, Gram Panchayat Mugaliya Chhap, Tehsil Huzur, Bhopal – 462 044, Madhya Pradesh",
  "Jaypee University of Engineering & Technology, AB Road, Raghogarh, Distt. Guna – 473 226 (M.P.)",
  "J.N.C.T Professional University, New Chouksey Nagar, Lambakheda, Berasia Road, Bhopal, Madhya Pradesh",
  "LNCT University, JK Town, Sarvadharam C Sector, Kolar Road, Bhopal – 462042, Madhya Pradesh",
  "LNCT Vidhyapeeth University, LNCT Campus, VillageKanadiya, Kanadiya Road, Indore, Madhya Pradesh",
  "Madhyanchal Professional University, Patel Group of Institutions Campus, Ratibad, Bhopal- 462044, Madhya Pradesh",
  "Mahakaushal University, Anthakheda, Chargawan Road, PostTilwara, Jabalpur, Madhya Pradesh",
  "Maharishi Mahesh Yogi Vedic Vishwavidyalaya, Jabalpur-482 001",
  "Malwanchal University, Index City, NH – 59 A, Nemawar Road, Near Khudel, District – Indore-452016, Madhya Pradesh",
  "Mandsaur University, Rewas Dewda Road, SH-31, Mandsaur – 458001, Madhya Pradesh",
  "Mangalayatan University, NH- 30, Mandla Road, Near Sharda Devi Mandir, Richai-Barela, Jabalpur-483001, Madhya Pradesh",
  "Mansarovar Global University, Village Gadia and Ratnakhedi, Block- Bilkisganj, Sehore, Madhya Pradesh",
  "Medi-Caps University, A.B. Road, Pigdamber, Rau, Indore453331, Madhya Pradesh",
  "SAM Global University, Agariya Chopda, Bilkhiriya, Bhopal, Madhya Pradesh",
  "Oriental University, Opp. Rewati Range Gate No. 1, Sanwer Road, PO Box No. 311, Vijay Nagar Post Office, Indore – 452 010, Madhya Pradesh",
  "People’s University, Bhanpur, Bhopal – 462 037 Madhya Pradesh",
  "P.K. University, Village – Thanara, Tehsil – Karera, NH – 27, Shivpuri, Madhya Pradesh-473551",
  "Prestige University, Gram Ringnodia, Indore-Ujjain, State Highway, Indore-453551, Madhya Pradesh",
  "Renaissance University, Survey Number-34/2, 51/1/1 Gram Reoti, Sanwer Road, Behind Aurobindo Hospital, Indore452015, Madhya Pradesh",
  "RKDF University, By-Pass Road, Near RGPC Campus, Bhopal, Madhya Pradesh",
  "Sage University, Kailod Kartal, Indore-Dewas Bypass Road, Rau, Indore- 452020, Madhya Pradesh",
  "Sanjeev Agrawal Global Educational University, Katara Extension, Sahara Bypass Road, Bhopal, Madhya Pradesh",
  "Sardar Patel University, Sardar Patel Knowledge City, Waraseoni Road, Dongariya, Balaghat 481331, Madhya Pradesh",
  "Sarvepalli Radhakrishnan University, NH-12, Hoshangabad Road, Jatkhedi, Bhopal, Madhya Pradesh",
  "Scope Global Skills University, Scope Campus, NH- 12, Bhaironpur, Near Misrod, Hoshangabad Road, Bhopal, Madhya Pradesh",
  "Shri Krishna University, NH- 86, Village Chowka, Sagar Road, Chhatarpur- 471001, Madhya Pradesh",
  "Shri Vaishnav Vidyapeeth Vishwavidyalaya, Sanwer Road, Indore-453111, Madhya Pradesh",
  "Shubham University, Semra Saiyad, Tehsil- Huzur, DistBhopal- 462010, Madhya Pradesh",
  "Sri Aurobindo University, SAIMS Campus, Indore-Ujjain State Highway, Near MR-10 Crossing, Sanwer Road, Indore - 453555, Madhya Pradesh",
  "Sri Satya Sai University of Technology & Medical Sciences, Bhopal-Indore Road, Opposite Pachama Oil Fed Plant, Pachama, Sehore – 466001, Madhya Pradesh",
  "Swami Vivekanand University, Sagar, Madhya Pradesh",
  "Symbiosis University of Applied Sciences, Bada Bangadda, Super Corridor, Indore – 453112, Madhya Pradesh",
  "Techno Global University, Lateri Road, Sironj (Near Gosala), Dist – Vidisha, Madhya Pradesh – 464 228",
  "Vikrant University, Gwalior, Village - Ratwai, Chitora Road, Bada Gaon, Morar, Gwalior - 474009, Madhya Pradesh",
  "VIT Bhopal University, Bhopal-Indore National Highway, Kothrikalan, Sehore- 466114, Madhya Pradesh",
  "Ajeenkya D.Y. Patil University, Charholi Badruk, Via Lohegaon, Pune-412105, Maharashtra",
  "Amity University, Mumbai - Pune Expressway, Bhatan, Post – Somathne, Panvel, Mumbai, Maharashtra – 410206",
  "ATLAS SKILLTECH UNIVERSITY Building A, CTS No.83, 83/1 to 19 of village Kurla, Taluka Kurla, LBS Marg, Kurla West, Mumbai – 400 070",
  "Chhatrapati Shivaji Maharaj University, Near Shedung Toll Plaza, Old Mumbai Pune Highway, Panvel, Navi Mumbai, Maharashtra",
  "D.Y. Patil Agriculture and Technical University, Talsande, Kolhapur, Maharashtra",
  "D Y Patil International University, Sector – 29, Pradhikaran, Akurdi, Pune – 411044, Maharashtra",
  "D.Y. Patil University, Ambi, Talegaon Dabhade, Pune, Maharashtra",
  "Flame University, GAT No. 1270, Taluka Mulshi, Village Lavale, Vadzai, Dist. Pune – 412115, Maharashtra",
  "G.H. Raisoni University, Badnera, Anjangaon, Bari Road, Amravati, Maharashtra - 444701",
  "Hyderabad (Sind) National Collegiate University, D.M. Harish Building, 47, Dr. R.G. Thadani Marg, Worli, Mumbai- 400018, Maharashtra",
  "K.J. Somaiya University, Vidyavihar (E), Mumbai - 400077, Maharashtra",
  "MGM University, MGM Campus, N-6, CIDCO, Aurangabad – 431003, Maharashtra",
  "MIT Art Design & Technology University, Rajbaug, Next to Hadapsar, Loni Kalbhor, Pune – 412201, Maharashtra",
  "MIT World Peace University, S.No. 124, Paud Road, Kothrud, Pune – 411038, Maharashtra",
  "NICMAR University, 25/1, Balewadi, N.I.A. Post Office, Pune- 411045, Maharashtra",
  "Pimpri Chinchwad University, Siona Building, S.No- 180, 181, 182, Vyllage- Sate, Taluka- Maval, Pune- 412106, Maharashtra",
  "Sandip University, Trimbak Road, Mahiravani, Nashik, Maharashtra",
  "Sanjay Ghodawat University, Pune-Bangalore Highway, Khandigao, Hatkanangale, Kolhapur- 416118, Maharashtra",
  "Somaiya Vidyavihar University, Somaiya Bhavan, 45-47, Mahatma Gandhi Road, Fort, Mumbai- 400001, Maharashtra",
  "Spicer Adventist University, Aundh Road, Gandshkhind Post, Pune – 411007, Maharashtra",
  "Sri Balaji University, S.No.55/2-7, Tathawade, Off Mumbai-Bengaluru Bypass, Pune- 411033, Maharashtra",
  "Symbiosis Skills and Open University, Village – Kiwale, Adjoining Pune Mumbai Expressway, Tal – Havely, Pune – 412101, Maharashtra",
  "Universal AI University, Kushivili, PO- Gaurkamath, Vadap, Karjat- 410201, District- Raigad, Maharashtra",
  "Vijaybhoomi University, Jamrung, Post- Ambivali, Taluka- Karjat, Dist- Raigad- 410201, Maharashtra",
  "Vishwakarma University, Survey No. 2, 3, 4, Laxmi Nagar, Kondhwa Budruk, Pune – 411 048, Maharashtra",
  "Sangai International University, Churachandpur, Manipur",
  "Manipur International University, MIU Palace, Ghari, Airport Road, Imphal – 795 140, Manipur",
  "Shija State Private University, Health Care & Research Institute Pvt. Ltd. Langol, Imphal West- 795004, Manipur",
  "St. Joseph University, Virgin Town, Khekiho-Zhimomi road, Makha, Dimapur, Nagaland",
  "The Global Open University, Wokha – 797 111, Nagaland",
  "The Institute of Chartered Financial Analysts of India University, 6th Mile, Sovima Village, Kohima Road, Dimapur – 797 112, Nagaland",
  "AIPH University, Pahala, On Bhubaneswar-Cuttack NH-16, Bhubaneswar- 72101, Odisha",
  "ASBM University, Shiksha Vihar, Bhola, Chandaka, Bhubaneswar- 754012, Odisha",
  "Asian International University, 6th Km, Jatni Bypass Road, Khordha- 752050, Odisha",
  "Birla Global University, IDCO Plot No. 2, Institutional Area, Village – Gothapatna, PS – Chandaka, Bhubaneswar – 751029, Odisha",
  "C.V. Raman Global University, Bidyanagar, Mahura, Janla, Bhubaneswar- 752054, Odisha",
  "Centurion University of Technology and Management, Village Alluri Nagar, PO R. Sitapur, Via- Uppalada, Paralakhemundi – 761 211, Gajapati, Odisha",
  "DRIEMS University, Tangi, Cuttack- 754022, Odisha",
  "GIET University, Gunupur- 765022, Dist Rayagada, Odisha",
  "Krupajal University, Pubasasan, Prachi Vihar, Bhubaneswar, District Khordha - 752101, Odisha",
  "Odisha University of Agriculture & Technology, Bhubaneswar- 751 003",
  "Sri Sri University, Bhubaneswar, Odisha",
  "Xavier University, Xavier Square, Bhubaneswar, Odisha",
  "Adesh University, NH-7, Barnala Road, Bathinda, Punjab",
  "Akal University, Talwandi Sabo – 151302, District Bathinda, Punjab",
  "Amity University, Block-D, Sector-82 Alpha, IT City, SAS Nagar, Mohali- 140306, Punjab",
  "Chandigarh University, Gharuan, The.-Kharar, Dt.- Mohali – 140 413, Punjab",
  "Chitkara University, Chandigarh-Patiala National Highway (NH-64), Village Jhansla, Patiala, Punjab – 140 401",
  "C.T. University, Ferozepur Road, Ludhiana-142024, Punjab",
  "D.A.V. University, Jalandhar-Pathankot National Highway-44, Village- Sarmastpur, Jalandhar, Punjab",
  "Desh Bhagat University, Amloh Road, Mandi Gobindgarh, Punjab",
  "GNA University, Village-Sri Hargobindgrh, Phagwara, Distt Kapurthala-144401, Punjab",
  "Guru Kashi University, Talwandi Sabo, Dt. Bhatinda, Punjab",
  "Lamrin Tech Skills University, Chandigarh-Jalandhar NH- 344A, 40 Kms from Chandigarh, Punjab",
  "Lovely Professional University, Jalandhar-Delhi National Highway (NH-1), Near Chehru Railway Bridge, Phagwara, District – Kapurthala, Punjab – 144 402",
  "Plaksha University, Block-B, Sector 101 A, IT City, SAS Nagar, Punjab- 140306",
  "Rayat Bahra University, VPO – Sahauran, Tehsil – Kharar, Distt. – Mohali, Punjab – 140 104",
  "RIMT University, Opposite Floating Restaurant, Sirhind Side, Mandi Gobindgarh-147301, Punjab",
  "Sant Baba Bhag Singh University, Village-Khiala, PO-Padhiana, Dist-Jalandhar-144030, Punjab",
  "Sri Guru Granth Sahib World University, Sri Fatehgarh Sahib, Punjab",
  "Amity University, Kant Kalwar, NH-11C, Jaipur-Delhi Highway, Jaipur – 303 002, Rajasthan",
  "Apex University, V.T. Road, Sector-5, Mansarovar, Jaipur- 302020, Rajasthan",
  "Baghwant University, Sikar Road, Ajmer, Rajasthan – 305 004",
  "Bhartiya Skill Development University, Plot No. 47, Knowledge City, Phagi, Jaipur- 302020, Rajasthan",
  "Bhupal Nobles University, Maharana Pratap Station Road, Sevashram Circle, Udaipur- 313001, Rajasthan",
  "Career Point University, Kota, Rajasthan",
  "Chhatrapati Shivaji Maharaj University, UID (1401340), NH-19, VPO-Kanhaiyawas, Teh-Bassi, Dist-Jaipur, Rajasthan",
  "Dr. K.N. Modi University, Plot-1, RIICO Industrial Area Ph-II, Newai, Distt. Tonk, Rajasthan – 304 021",
  "Eminent Academy, (Private University) Shivrati Nagar, Bhuwana, Udaipur – 313001, Rajasthan",
  "Geetanjali University, Udaipur, Rajasthan",
  "G.L.S. University, (Private University) UID (1401349), 405, 4th Floor, Apex Tower, Tonk Road, Jaipur, Rajasthan",
  "Haridev Joshi University of Journalism and Mass Communication, Khasa Kothi Campus, Jaipur, Rajasthan",
  "Homoeopathy University, Saipura, Sanganer, Jaipur – 302 029, Rajasthan",
  "ICFAI University, Khasra No. 505/1, Village-Jamdoli, Agra Road, Jaipur – 302 031, Rajasthan",
  "I.I.M.T. University, UID (1401351), SP-40, RIICO Industrial Area, Neemrana, Dist-Alwar, Rajasthan",
  "IIS, (Deemed to be University), Gurukul Marg, SFS, Mansarovar, Jaipur-302020, Rajasthan",
  "Institute of Advanced Studies in Education, Gandhi Vidya Mandir, Sardarshahr – 331 403, Distt. Churu, Rajasthan",
  "Jagan Nath University, NH-12, Chaksu Bypass, Tonk Road, Jaipur-303901, Rajasthan",
  "Jaipur National University, Jagatpura, Jaipur, Rajasthan",
  "Janardan Rai Nagar Rajasthan Vidyapeeth, Pratap Nagar, Udaipur, Rajasthan",
  "JAYOTI VIDYAPEETH WOMEN'S UNIVERSITY, Vedant Gyan Valley, Village-Jharna, Mahala Jobner Link Road, Jaipur Ajmer Express Way, NH-8, Jaipur-303 122, Rajasthan",
  "J.E.C.R.C. University, Jaipur, Rajasthan",
  "J.K. Lakshmipat University, Laliya Ka Vas, PO Mahapura, Ajmer Road, Jaipur – 302 026, Rajasthan",
  "J.N.V. University, Jodhpur- 342 011, Rajasthan",
  "Lords University, Alwar-Tijara-Delhi Highway, Chikani, Alwar- 301028, Rajasthan",
  "Madhav University, Madhav University, “Madhav Hills”, Opp. Banas River Bridge Toll, NH-14, Village-Wada/Bhujela, Panchayat Samiti – Bharja, Tehsil – Pindwara, Abu Road, District-Sirohi, Rajasthan – 307026",
  "Maharaja Ganga Singh University, National Highway No. - 15, Jaisalmer Road, Bikaner-334004, Rajasthan",
  "Maharana Pratap University of Agriculture & Technology, Udaipur - 313 001, Rajasthan",
  "Maharshi Dayanand Saraswati University, Ajmer- 305 009, Rajasthan",
  "Mahatma Jyoti Rao Phoole University, SP-2 & 3, Kant Kalwar, RIICO Industrial Area, NH-8, Near Achrol, Jaipur, Rajasthan",
  "Mewar University, NH 79, Gangrar, Chittorgarh, Rajasthan",
  "Mody University of Science and Technology, Lakshmangarh, District Sikar Rajasthan",
  "Mohan Lal Sukhadia University, Pratap Nagar, Udaipur- 313 001, Rajasthan",
  "NIMS University, Shobha Nagar, Jaipur – 303 001, Rajasthan",
  "NIIT University, Neemrana, Rajasthan",
  "OPJS University, Rawatsar, Kunjila, Tehsil-Rajgarh, Distt. – Churu, Rajasthan",
  "Pacific Medical University, Bhilon Ka Bedla, Pratap Pura, National Highway 27, Udaipur- 313001, Rajasthan",
  "Pacific Academy of Higher Education & Research University, (PAHER) Pacific Hills, Airport Road, Pratap Nagar Extension, Debari, Udaipur – 313 024, Rajasthan",
  "Poornima University, Ramchandrapura, Sitapura Extension, Jaipur, Rajasthan",
  "Pratap University, Sunderpura (Chandwaji), Amer, Delhi-Mumbai Highway, Jaipur, Rajasthan",
  "Raffles University, Japanese Zone, National Highway 8, Neemrana-201 705, Rajasthan",
  "R.N.B. Global University, RNB Global City, Ganganagar Road, Bikaner- 334601, Rajasthan",
  "Shri Jagdishprasad Jhabarmal Tibrewala University, Vidya Nagari, Jhunjhunu-Churu Road, Chudela, District Jhunjhunu-333001, Rajasthan",
  "Shri Khushal Das University, Suratgarh Road, Near Toll Plaza, Bikaner, Rajasthan",
  "Shridhar University, Pilani Chirawa Road, Pilani Rajasthan – 333 031",
  "Singhania University, Pacheribari, Dt. Jhunjunu – 333515, Rajasthan",
  "Sir Padmapat Singhania University, Bhatewar Udaipur – 313 601, Rajasthan",
  "Suresh Gyan Vihar University, Mahal Jagatpura, Jaipur, Rajasthan",
  "Sunrise University, Bagad Rajput, Tech. Ramgarh, Alwar, Rajasthan",
  "Tantia University, Hanumangarh Road, Sri Ganganagar – 335 002, Rajasthan",
  "University of Engineering & Management, Gurukul, 22 Kms. From Chomu on Sikar Road, NH-11, Jaipur – 303 807, Rajasthan",
  "University of Kota, Near Kabir Circle, MBS Marg, Kota-324005, Rajasthan",
  "University of Rajasthan, Jaipur-302 004, Rajasthan",
  "Vardhman Mahaveer Open University, Rawat Bhata Road, Akhelgarh, Kota-324 010, Rajasthan",
  "Vivekananda Global University, Sector 36, NRI Road, Sisyawas, Jagatpura, Jaipur – 303 012, Rajasthan",
  "Khangchendzonga State University, (Formerly Sikkim State University), Tadong, Gangtok, Sikkim- 737102",
  "Medhavi Skills University, Singtam Campus, Topakhani, Lower Mareo, East Sikkim- 737134",
  "Shri Ramasamy Memorial University, 5th Mile, Tadong, Ranipool, Gangtok, Sikkim – 737 102",
  "Sikkim Alpine University, Kamrang, Namchi, South Sikkim- 737126",
  "Sikkim Global Technical University, Shibing, Pakyong, Sikkim",
  "Sikkim International University, Sribadam, West Sikkim- 737111",
  "Sikkim Manipal University, 5th Mile, Tadong, Gangtok- 737 102, Sikkim",
  "Sikkim Professional University, (Formerly Vinayaka Missions Sikkim University), Plot No. 438, N-312 Sang Phatak Road, Middle Tadong, PO Daragaorn, Tadong, East Sikkim - 237 102",
  "Sikkim Skill University, Passi, Namthang, South Sikkim- 737137",
  "The Institute of Chartered Financial Analysts of India University, (ICFAI) Ranka Road, Lower Sichey, Gangtok- 737 101, Sikkim",
  "Academy of Maritime Education and Training, 135, East Coast Road, Kanathur, Chennai-603112, Tamil Nadu",
  "Amrita Vishwa Vidyapeetham, Amritanagar, Coimbatore-641 112, Tamil Nadu",
  "Avinashilingam Institute for Home Science & Higher Education for Women, Coimbatore-641 043, Tamil Nadu",
  "Bharath Institute of Higher Education & Research, 173, Agharam Road, Selaiyur, Chennai-600 073, Tamil Nadu",
  "B.S. Abdur Rahman Crescent Institute of Science and Technology, Seethakathi Estate, GST Road, Vandalur, Chennai-600 048, Tamil Nadu",
  "Chennai Mathematical Institute, H1, SIPCOT IT Park, Siruseri, Kelambakkam- 603 103, Tamil Nadu",
  "Chettinad Academy of Research and Education (CARE), Rajiv Gandhi Salai, Padur, Kelambakkam, Kancheepuram District, Tamil Nadu",
  "Dhanalakshmi Srinivasan University, NH-45, Trichy Chennai Trunk Road, Samayapuram, Tiruchirappalli, Tamil Nadu- 621112",
  "Dr. M.G.R. Educational and Research Institute, Periyar E.V.R. High Road, (NH-4 Highway), Maduravoyal, Chennai-600 095, Tamil Nadu",
  "Hindustan Institute of Technology and Science, Rajiv Gandhi Salai (OMR), Padur, Kelambakkam, Chennai-603 103, Tamil Nadu",
  "Kalasalingam Academy of Research and Higher Education, Anand Nagar, Krishnankoil, Virudhunagar-626 190, Via Srivilliputhr, Tamil Nadu",
  "Karpagam Academy of Higher Education, Pollachi Main Road, Coimbatore, Tamil Nadu",
  "Karunya Institute of Technology and Sciences, Karunya Nagar, Coimbatore-641 114, Tamil Nadu",
  "Meenakshi Academy of Higher Education and Research, No. 12, Vembuliamman Koil Street, West K.K. Nagar, Chennai-600 078, Tamil Nadu",
  "Noorul Islam Centre for Higher Education, Kumaracoil, Thuckalay, Kanyakumari District, Tamil Nadu-629 175",
  "Periyar Maniammai Institute of Science & Technology (PMIST), Periyar Nagar, Vallam, Thanjavur-613 403, Tamil Nadu",
  "Ponnaiyah Ramajayam Institute of Science & Technology (PRIST), Yagappa Chavadi, Thanjavur-614 904, Tamil Nadu",
  "S.R.M. Institute of Science and Technology, SRM Nagar, Kattankulathur-603 203, Kancheepuram District, Tamil Nadu",
  "Sai University, City Campus, SP Infocity, Block-A, 4th Floor, 40 MGR Salai, Perungudi, Chennai- 600096, Tamil Nadu",
  "Sathyabama Institute of Science and Technology, Jeppiaar Nagar, Rajiv Gandhi Salai, Chennai-600 119, Tamil Nadu",
  "Saveetha Institute of Medical and Technical Sciences, Post Box No. 6, No. 162, Poonamalle High Road, Velappanchavadi, Chennai-600 077, Tamil Nadu",
  "Shanmugha Arts, Science, Technology, Research & Academy (SASTRA), Thirumalaisamudram, Thanjavur-613 401, Tamil Nadu",
  "Shiv Nadar University, Rajiv Gandhi Salai (OMR), Kalavakkam, Chennai- 603110, Tamil Nadu",
  "Sri Chandrasekharendra Saraswathi Vishwa Mahavidyalaya, Enathur, Kancheepuram-631 561, Tamil Nadu",
  "Sri Ramachandra Institute of Higher Education and Research, 1, Ramachandra Nagar, Porur, Chennai-600 116, Tamil Nadu",
  "St. Peter’s Institute of Higher Education and Research, Chennai, Tamil Nadu",
  "Vel Tech Rangarajan Dr. Sagunthala R & D Institute of Science and Technology, 42, Avadi-Vel Tech Road, Avadi, Chennai-600062, Tamil Nadu",
  "Vellore Institute of Technology, Vellore-632 014, Tamil Nadu",
  "Vels Institute of Science, Technology & Advanced Studies (VISTAS), Velan Nagar, P.V. Vaithiyalingam Road, Pallavaram, Chennai-600117, Tamil Nadu",
  "Vinayaka Mission's Research Foundation, Sankari Main Road, NH 47, Ariyanoor, Salem-636 308, Tamil Nadu",
  "Anurag University, Venkatapur (V), Ghatkesar (M), Medchal (Malkajgiri), Hyderabad, Telangana",
  "Chaitanya University, Kishanpura, Hanamkonda, Warangal- 506001, Telangana",
  "CMR University, CMR Technical Campus, Kandlakoya, Medchal Road, Hyderabad, Telangana",
  "Dhanalakshmi Srinivasan University, Hyderabad, Telangana",
  "G.N.R. University, R.R. District, Telangana",
  "Guru Nanak University, Hyderabad, Telangana",
  "Kaveri University, Gowraram Village, Wargal Mandal, Siddipet District, Telangana",
  "Malla Reddy University, Maisammaguda, Dulapally, Kompally, Medchal Malkajgiri District, Telangana",
  "Maulana Azad National Urdu University, Gachibowli, Hyderabad, Telangana",
  "Woxsen University, Woxsen Campus, Kamkole, Sadasivpet, Medak District, Telangana",
  "ICFAI Foundation for Higher Education, Hyderabad, Telangana",
  "ICFAI University, Tripura",
  "Maharaja Bir Bikram University, Agartala, Tripura",
  "Techno India University, Tripura",
  "Amity University, Noida, Uttar Pradesh",
  "Babu Banarasi Das University, Lucknow, Uttar Pradesh",
  "Bareilly International University, Bareilly, Uttar Pradesh",
  "Bennett University, Greater Noida, Uttar Pradesh",
  "Era University, Lucknow, Uttar Pradesh",
  "F S University, Shikohabad, Dist. Firozabad, Uttar Pradesh",
  "Galgotias University, Greater Noida, Uttar Pradesh",
  "GLA University, Mathura, Uttar Pradesh",
  "IFTM University, Moradabad, Uttar Pradesh",
  "IIMT University, Meerut, Uttar Pradesh",
  "Invertis University, Bareilly, Uttar Pradesh",
  "Jaypee Institute of Information Technology, Noida, Uttar Pradesh",
  "JS University, Shikohabad, Firozabad, Uttar Pradesh",
  "Maharishi University of Information Technology, Lucknow, Uttar Pradesh",
  "Mangalayatan University, Aligarh, Uttar Pradesh",
  "Mohammad Ali Jauhar University, Rampur, Uttar Pradesh",
  "Monad University, Hapur, Uttar Pradesh",
  "Noida International University, Greater Noida, Uttar Pradesh",
  "Sharda University, Greater Noida, Uttar Pradesh",
  "Shiv Nadar University, Greater Noida, Uttar Pradesh",
  "Shobhit University, Meerut, Uttar Pradesh",
  "Shri Ramswaroop Memorial University, Lucknow-Deva Road, Barabanki, Uttar Pradesh",
  "Other"
];

export const BLOOD_GROUPS = [
  "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"
];

export const LANGUAGES = [
  "Marathi", "Hindi", "English", "Assamese", "Bengali", "Bodo", "Dogri", "Gujarati", 
  "Kannada", "Kashmiri", "Konkani", "Maithili", "Malayalam", "Meitei (Manipuri)", 
  "Nepali", "Odia", "Punjabi", "Sanskrit", "Santali", "Sindhi", "Tamil", "Telugu", "Urdu"
];

export const DISABILITY_TYPES = [
  "Blindness", "Low-Vision", "Locomotor Disability", "Hearing Impairment", 
  "Intellectual Disability", "Mental Illness", "Autism Spectrum Disorder", 
  "Cerebral Palsy", "Muscular Dystrophy", "Chronic Neurological Conditions", 
  "Specific Learning Disabilities", "Multiple Sclerosis", "Speech and Language Disability", 
  "Thalassemia", "Hemophilia", "Sickle Cell Disease", "Multiple Disabilities", "Other"
];

export const ACCOUNT_TYPES = ["Saving", "Current"];
